import binascii
from flask import current_app as app
import codecs

class Seller_Review:
    def __init__(self, id, uid, sid, review_time, review_rating, review = ""):
        self.id = id
        self.uid = uid
        self.sid = sid
        self.review_time = review_time
        self.review_rating = review_rating
        self.review = review
        #self.review_image = review_image

    @staticmethod
    # Function to get all product reviews mapped to a user id given a user id
    def get_review_by_id(id):
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE id=:id
            ''',
            id=id
        )
        return rows
    
    @staticmethod
    # Function to get all product reviews mapped to a user id given a user id
    def get_review_by_uid_sid(uid, sid):
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE uid=:uid
            AND seller_id=:sid
            ''',
            uid=uid,
            sid=sid
        )
        return [Seller_Review(*row) for row in rows][0]

    @staticmethod
    # Function to get all product reviews mapped to a user id given a user id
    def get_all_by_uid(uid):
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE buyer_id = :uid
            ORDER BY review_time DESC
            ''',
            uid=uid
        )
        return [Seller_Review(*row) for row in rows]
    
    @staticmethod
    def get_all_by_sid(sid):
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE seller_id=:sid
            ORDER BY review_time DESC
            ''',
            sid = sid
        )
        return [Seller_Review(*row) for row in rows]
    
    @staticmethod
    def find_seller_by_product(id):
        rows = app.db.execute(
            '''
            SELECT user_id
            FROM Products
            WHERE id=:id
            ''',
            id=id
        )
        return rows[0]
    
    @staticmethod
    def get_all_by_pid_order_by_likes(sid):
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE sid = sid
            ORDER BY thumbs_up DESC
            ''',
            sid=sid
        )
        return [Seller_Review(*row) for row in rows]
    
    def get_review(uid, pid):
        # TODO
        pass
    
    @staticmethod
    def add_review(uid, sid, time, rating, review):
        # Convert image data to hexadecimal string
        #img_hex = binascii.hexlify(img).decode('utf-8') if img else None

        app.db.execute(
            '''INSERT INTO Seller_Reviews (buyer_id, seller_id, review_time, rating, review) 
            VALUES (:uid, :sid, :time, :rating, :review)''',
            uid=uid,
            sid=sid,
            time=time,
            rating=rating,
            review=review
        )

    #returns a boolean that is true if user already reviewed this seller, and false otherwise
    def check_review(uid, sid):
        #fetches the tuples in Reviews where uid=uid and sid=sid
        rows = app.db.execute (
            '''
            SELECT *
            FROM Seller_Reviews
            WHERE buyer_id = :uid
            AND seller_id = :sid
            ''',
            uid=uid,
            sid=sid
        )
        #Check if the array of rows is greater than 0. If so, then it exists in Reviews already
        row_list = [Seller_Review(*row) for row in rows]
        if len(row_list) > 0:
            return True
        return False

    def update_review(uid, sid, review, rating, time):
        #change your review
        pass

    def delete_review(rid):
        #TODO delete existing review
        app.db.execute (
            '''DELETE FROM Seller_Reviews 
            WHERE id=:rid''',
            rid=rid
        )

    def update_feedback(id, thumbs_up, thumbs_down):
        app.db.execute (
            '''
            UPDATE Seller_Reviews
            SET thumbs_up = :thumbs_up, thumbs_down = :thumbs_down
            WHERE id=:id
            ''',
            id=id,
            thumbs_up=thumbs_up,
            thumbs_down=thumbs_down
        )

 

"""
CREATE TABLE Reviews(
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyer_id INT NOT NULL REFERENCES Users (id),
    product_id INT NOT NULL REFERENCES Products(id), --do I need REFERENCES?,
    review_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    thumbs_up INT NOT NULL,
    thumbs_down INT NOT NULL,
    img BYTEA NOT NULL,
    review VARCHAR(255) 
);
"""
    
   